
# Makefile for the kernel CAN serial device example.
#
# Advantech eAutomation Division
#


CC=gcc
all: 
	@$(CC) readCAN.c -o readCAN
	@$(CC) sendCAN.c -o sendCAN
clean:
	-@rm -f readCAN \
	sendCAN

	


